# Generated by Django 5.2.7 on 2025-10-20 15:53

import django.core.validators
import loans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=13, unique=True, validators=[loans.models.validate_isbn]
            ),
        ),
    ]
